const vehicles = [
  {
    name: 'Iveco',
    price: 50,
    year: 2014,
    mileage: 4980,
    transmission: 'Manual',
    isNew: true,
    img: 'https://avatar-moving.com/sites/default/files/inline-images/moving-cars-on-car-carrier.jpg',
  },
  {
    name: 'Man',
    price: 6700,
    year: 2013,
    mileage: 1200,
    transmission: 'Manual',
    isNew: false,
    img: 'https://image.made-in-china.com/202f0j00DOpQLkjMahzt/Heavy-Duty-Double-Tri-Axle-for-6-8cars-Transporting-Car-Carrier-Trailers.jpg',
  },
  {
    name: 'Scania',
    price: 7000,
    year: 2017,
    mileage: 84500,
    transmission: 'Manual',
    isNew: false,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSzNJ3I8IOVa8byRT_kx__ag_KNLi2WX7v2-XOKB07Rr635zJSj&usqp=CAU',
  },
  {
    name: 'Daf',
    price: 6700,
    year: 2013,
    mileage: 1200,
    transmission: 'Manual',
    isNew: false,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQgXhAVJZ42n4nJ2rm7x7cGyzFrdmnHuyyeEs9Bgp-PwgMWV_Ty&usqp=CAU',
  },
  {
    name: 'Volkswagen Atlas Cross',
    price: 11300,
    year: 2014,
    mileage: 4980,
    transmission: 'Manual',
    isNew: true,
    img: 'https://eamonmclaughlin.com/wp-content/uploads/2018/03/multicar-transporter-mclaughlin-car-transport.jpg',
  },
  {
    name: 'Chevrolet',
    price: 70,
    year: 2014,
    mileage: 4980,
    transmission: 'Manual',
    isNew: true,
    img: 'https://ptsl.co.nz/images/PTS_Group_Trasporting_Types_of_Vehicles_cars_2.jpg',
  },
  {
    name: 'Iveco',
    price: 4800,
    year: 2011,
    mileage: 76500,
    transmission: 'Automatic',
    isNew: false,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ7JoHn56qHVFyzXc9awVXXQ5WUFAs0Ui73AF1IUWU4NYohVAXy&usqp=CAU',
  },
  {
    name: 'Volkswagen',
    price: 12870,
    year: 2011,
    mileage: 84500,
    transmission: 'Manual',
    isNew: false,
    img: 'https://ptsl.co.nz/images/NewZealandWide2.jpg',
  },
];

export default vehicles;
